theochem/Selector

.github/CONTRIBUTING.md
README.md

This PR adds version numbers for different packages, which will help people to work in the same environment. This fixes #11.

Add package information for development

---

DiverseSelector/base.py
DiverseSelector/utils.py
tox.ini

Add API draft

---

DiverseSelector/base.py

There are some changes to the API hierarchy that I propose (did my best to satisfy both functional and OOP approaches):
1. Create only one abstract class called Selector
2. Create 2 (potentially more) child classes that will be used for implementing different families of algorithms: clustering and brute force selectors. Potentially might add one more that is baed on Monte Carlo methods
3. Add some minor tweaks for the methods that shouldn't depend on chosen selector (IO such as `read_excel`, `to_excel`)
4. Specified documentation
Any ideas/proposition on how to make it better? 
@PaulWAyers @fwmeng88

rewrite API

---

DiverseSelector/feature.py
DiverseSelector/utils.py
requirements.txt

This PR adds a feature generation module.

Add feature generation module

---

DiverseSelector/base.py
DiverseSelector/metric.py

We use one parent class for both dissimilarity- and clustering-based methods.

Refactor base classes

---

DiverseSelector/base.py
DiverseSelector/dissimilarity_based.py
DiverseSelector/metric.py

This is the initial draft and is subject to change soon.

Add DSCS draft

---

.github/workflows/ci_codecov.yml
DiverseSelector/test/test_DissimilarityBased.py
requirements.txt

This PR fixes the problem of not being able to locate the package modules.

Fix file path

---

DiverseSelector/base.py

The original implementation is missing the actual loading data, which is problematic.

Fix missing `feature` in base class

---

DiverseSelector/dissimilarity_based.py
DiverseSelector/test/test_DissimilarityBased.py
tox.ini

Added dissimilarity algorithm prototypes for brute force, directed sphere exclusion, and optisim. I plan to further optimize the functions for run-time execution and edit minor parts of the functionality. @fwmeng88 Please let me know if you have any feedback so far.

Add bruteforce, DISE, optisim dissimilarity methods

---

DiverseSelector/metric.py

Added references to the Metrics.py file (ACS style).

Add references

---

DiverseSelector/base.py
DiverseSelector/metric.py
DiverseSelector/test/test_metrics.py

This PR builds up a new wrapper function for computing the molecular diversity.

Add wrapper to compute diversity

---

DiverseSelector/base.py
DiverseSelector/distance.py
DiverseSelector/diversity.py
DiverseSelector/test/test_metrics.py
DiverseSelector/utils.py

This can make the structure cleaner.

Split metric.py into two modules

---

DiverseSelector/base.py
DiverseSelector/test/test_selectors.py

@alnaba1 I commented out tests for the classes `DirectedSphereExclusion` and `GridPartitioning`

add and fixed tests

---

DiverseSelector/selectors.py
DiverseSelector/test/test_selectors.py
DiverseSelector/utils.py

Fixed the issue with grid partitioning selecting more molecules than needed, refactored the predict_radius function, added documentation for sphere exclusion, optisim, grid partitioning.

Fix grid partitioning, refactor, add documentation

---

DiverseSelector/selectors.py
DiverseSelector/test/test_selectors.py

Added class for the MaxSum algorithm along with tester files.

Add MaxSum class and tester

---

DiverseSelector/features.py
DiverseSelector/test/test_feature.py

Add feature agumentation to support stratified sampling, fix #80

---

DiverseSelector/base.py
DiverseSelector/selectors.py
DiverseSelector/test/test_selectors.py

Implements KDTree structuring in OptiSim to significantly improve algorithm performance.

Improve Optisim Performance

---

DiverseSelector/diversity.py

The original re-factorization was not complete which caused errors. This PR fixes it.

Rename `total_diversity_volume` --> `hypersphere_overlap_of_subset`

---

.coveragerc
DiverseSelector/distance.py
DiverseSelector/test/test_distance.py

Address post pull request task list todos in [Issue 125](https://github.com/theochem/DiverseSelector/issues/125)

Polish dist

---

DiverseSelector/methods/dissimilarity.py

The number of upper size means the max number we selested. upper_size = tol*size, if tol=5.0, the upper_size will be larger than we want.

Fix tolerance value

---

.github/workflows/ci_codecov.yml
.github/workflows/ci_tox.yml
.github/workflows/website_auto.yml
requirements.txt
requirements_dev.txt
setup.py
tox.ini

THe original test failed because of the wrong test folder directory.

Update CI configurations

---

.github/workflows/website_auto.yml

The original setting fails to update the website.

Fix the problem of pushing website with GitHub Actions

---

DiverseSelector/diversity.py
DiverseSelector/tests/test_diversity.py

The original implementation was not correct and this PR fixes the problem, #67.

Fix shannon entropy

---

.github/workflows/ci_codecov.yml
.github/workflows/ci_tox.yml
.github/workflows/website_auto.yml

Use `setup-python` v5 in GitHub Actions

---

selector/diversity.py
selector/tests/test_diversity.py

This PR addresses the problem.

Fix the errors when only some feature columns are constants for `wdud`

---

.github/workflows/ci_codecov.yml

https://github.com/codecov/codecov-action/issues/1487

Fix the failing codecov upload

---

pyproject.toml

This PR updates the dependency version.

Update `scipy` and `pytest` version in pyproject.toml

---

selector/diversity.py
selector/methods/partition.py
selector/tests/test_diversity.py

This is just a simple renaming fix.

Rename "hypersphere overlap of subset" to "hypersphere_overlap"

---

selector/methods/tests/test_distance.py
selector/methods/tests/test_partition.py
selector/methods/tests/test_sim.py

This PR addresses the failing tests that arose from https://github.com/theochem/Selector/pull/223.
I also renamed the instance names to `collector` instead of `selector,` which is taken by the package name already. Please let me know if you prefer a different name. @FarnazH @Ali-Tehrani @marco-2023

Fix failing tests for `DISE`

---

selector/measures/init.py
selector/measures/similarity.py

Added the init file to measures subpackage.
Added several similarity measures to the measure subpackage.  These are now untested, I will add several formal tests later.

Add init to measures & similarity measures.

---

notebooks/tutorial_diversity_measures.ipynb

This PR adds the diversity measurements.

Add tutorial notebook for diversity measures

---

README.md
book/content/intro.md

Updated the README.md and docs.

Add link to webserver
