theochem/Selector

DiverseSelector/metric.py, DiverseSelector/test/test_metrics.py
Gini coefficient before was based on the probability distribution on each molecule. Changed it to match the paper where the probability distribution is the features.  #72
=> Fix so feature is the probability dist in gini

DiverseSelector/selectors.py
Because we didn't update the dimension in the original codes, this leads to a problem when using the grid partitioning. This PR fixes that problem.
=> Fix dimensionality bug grid partitioning

DiverseSelector/selectors.py
Implements improved behaviour when given initial radius for `Optisim` and `DirectedSphereExclusion` algorithms according to the idea by @FanwangM in #108:
> If the user specifies both, the number of molecules should be
> 
> initial radius --> change the radius --> the right number of molecules.
=> Improve behavior when given radius, add warning when provided incorrect number of molecules.

DiverseSelector/selectors.py
This fixes the problem of importing,
```python
from DiverseSelector.selectors import MaxMin, MaxSum, OptiSim, DirectedSphereExclusion, GridPartitioning, KDTree
```
=> Add __all__ in `selectors.py`

README.md
This simplifies the number of badges we have for the Python versions.
=> Clean Python version badge

DiverseSelector/diversity.py, DiverseSelector/methods/dissimilarity.py, DiverseSelector/methods/partition.py, DiverseSelector/methods/tests/test_partition.py, DiverseSelector/methods/utils.py
Optimize the Directed Sphere exclusion code, as well as add comments and testing to address [issue #133](https://github.com/theochem/DiverseSelector/issues/133)
=> Cleanup of Directed Spheres class

DiverseSelector/methods/dissimilarity.py, DiverseSelector/methods/partition.py
The select_from_cluster method did not use the data from the cluster labels. Because of this, the algorithm used the whole data instead of the samples of the cluster from which the selection should occur. The algorithm then failed if cluster labels were used.
This PR fixes #154
=> Debug DirectedSphereExclusion

.github/workflows/ci_codecov.yml, .github/workflows/ci_tox.yml, .github/workflows/website_auto.yml, DiverseSelector/diversity.py, DiverseSelector/test/test_diversity.py
The original white spaces can be confusing for users.
=> Replace white spaces with underscore for diversity measurement methods

.github/workflows/website_auto.yml
The original configuration is not publishing the website.
=> Update website deployment GitHub Action

DiverseSelector/converter.py, DiverseSelector/tests/test_converter.py
Also fixed the failing tests because of non-symmetric matrix used. This PR is the final attempt to address #123.
=> Add 2D symmetric array checking for `converter` module

selector/diversity.py, selector/tests/test_diversity.py
The hypersphere_overlap_of_subset method failed if the data had any redundant feature. This is a pretty common case, e.g. finding a diverse set of alcohols (all binary chains will have a common feature). This was making grid_partitioning methods to fail.
The fix removes redundant coordinates before normalizing and computing diversity. Now it only fails if all binary chains in the data are the same.
=> Add fix to hypersphere_overlap_of_subset

.github/workflows/ci_codecov.yml
This PR fixes the outdated `codecov-action` version.
=> Upgrade codecov-action version 4.x

selector/similarity.py, selector/tests/test_similarity.py
Adding the support of scaled similarity matrix in the similarity module by implementing the method. 
Considering $S(i,j)$ denotes the similarity between $i^{th}$ sample and $j^{th}$ sample, formula used to calculate scaled similarity matrix is
$S(i,j)={S(i,j)\over\sqrt{S(i,i)S(j,j)}}$
- Implemented the method `scaled_similarity_matrix()`
- Added the tests and docstrings
Fixes #122
=> [Similarity module] Scaled similarity support

.github/workflows/ci_tox.yml, requirements.txt, requirements_dev.txt, setup.py
https://github.com/actions/setup-python/issues/825
=> Fix the failing testing because of the architecture change of MacOS

.github/workflows/ci_codecov.yml
This fixes the problem of https://github.com/theochem/Selector/actions/runs/9666084225/job/26664757592.
=> Add new environment token to fix the failing updating coverage report

.github/workflows/ci_codecov.yml
This issue is discussed in https://github.com/codecov/codecov-action/issues/1487.
Two sample fixes, https://github.com/MFlowCode/MFC/pull/500 and https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1686
=> Fix failing `CodeCov` report

selector/diversity.py, selector/tests/test_diversity.py
I also updated the tests. The natural logarithm is used instead of the logarithm base 10 (common logarithm) because this is only a constant scaling, which does not affect the relative ranking of diversity measures.
The numerical stability issue is explained in https://github.com/theochem/Selector/issues/229.
=> Fix the numerical stability issue of log det function (fixes #229)

selector/methods/distance.py
In DISE algorthim, the `ref_index` was not included as a selected sample, and its neighbors were not excluded. I believe this was not a desired feature, so this PR fixed that. Feel Free to let me know what you think.
=> Exclude neighbours of the ref_index in DISE algorithm

selector/methods/partition.py, selector/methods/tests/test_partition.py
The index of each neighbor of KD-Tree query results can be integer or array of integers. The original implementation works for the array of integers, but not including the integer case. This commit fixes the problem.
More explanations were provided in https://github.com/theochem/Selector/issues/236.
=> Fix the KD-Tree query return

selector/diversity.py, selector/methods/base.py
The functions in `diversity` module use incosistent argmnet names of `x` (lower case) or `X` (upper case). This PR fixes this problem.
=> Use lower case argument names following numpy

selector/methods/distance.py, selector/methods/tests/test_distance.py
The original implementation does not support initial data points but only the medoid. Now we support
This is achieved by having a shared function called 'get_initial_selections'.
=> Add support of distance function and flexible reference index for `DISE`

selector/methods/distance.py, selector/methods/tests/test_distance.py
=> Fix the building reference index when `ref_index` is None in `DISE`

selector/methods/distance.py, selector/methods/tests/test_distance.py
This PR removes the redundant kwargs for distances function as the user can always define it in the lambda function.
=> Clean up the distance function kwargs for `DISE`

notebooks/tutorial_distance_based.ipynb, notebooks/tutorial_partition_based.ipynb, notebooks/tutorial_similarity_based.ipynb
These changes correspond to the update in the links to the methods used in the selector package in the following tutorial notebooks:
- Tutorial Distance-Based Selectors
- Tutorial Partition-Based Selectors
- Tutorial Similarity Based Selectors
=> Hyperlink Update in Tutorial Notebooks

selector/methods/distance.py
The original implementation sets `ref_index` of `OptiSim` to be None, which can be problematic when the `fun_dist` is None. Setting it to be 0 fixes the problem.
=> Fix ref_index of `OptiSim`
